//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace guahao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public System.DateTime date { get; set; }
        public int hosipital_id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual doctor doctor { get; set; }
    }
}
